# -*- coding: utf-8 -*-
"""Core wrapper for UIAutomation operations."""

import ctypes
import logging
import time
import uuid
from typing import Optional, Any, Dict, List, Tuple

import uiautomation as auto

from .config import config
from .models import ControlInfo, ControlSelector, ConfirmationRequest

logger = logging.getLogger(__name__)

# Control registry for handle→token mapping (solves UWP/Chrome/Qt handle=0 issue)
_control_registry: Dict[str, Tuple[auto.Control, float]] = {}
_registry_max_size = 500
_registry_ttl = 300  # seconds


def is_admin() -> bool:
    """Check if running with administrator privileges."""
    try:
        return ctypes.windll.shell32.IsUserAnAdmin()
    except Exception:
        return False


def check_admin() -> None:
    """Check admin privileges and warn if not available."""
    if config.admin_check and not is_admin():
        logger.warning(
            "Not running as administrator. Some operations may fail. "
            "Consider running with admin privileges."
        )


# Pending confirmations storage
_pending_confirmations: Dict[str, ConfirmationRequest] = {}


def create_confirmation(tool: str, details: Dict[str, Any], message: str) -> ConfirmationRequest:
    """Create a confirmation request for a dangerous operation.

    Args:
        tool: Name of the tool requesting confirmation.
        details: Details about the operation (e.g., window handle, process ID).
        message: Human-readable message explaining the operation.

    Returns:
        ConfirmationRequest with a unique token for tracking.
    """
    token = str(uuid.uuid4())[:8]
    request = ConfirmationRequest(
        tool=tool,
        details=details,
        message=message,
        confirmation_token=token,
    )
    _pending_confirmations[token] = request
    return request


def confirm_operation(token: str, approved: bool) -> Optional[ConfirmationRequest]:
    """Confirm or reject a pending operation.

    Args:
        token: The confirmation token from the original request.
        approved: Whether the operation was approved.

    Returns:
        The original ConfirmationRequest if approved, None otherwise.
    """
    request = _pending_confirmations.pop(token, None)
    if request and approved:
        return request
    return None


def get_pending_confirmation(token: str) -> Optional[ConfirmationRequest]:
    """Get a pending confirmation without removing it.

    Args:
        token: The confirmation token to look up.

    Returns:
        The ConfirmationRequest if found, None otherwise.
    """
    return _pending_confirmations.get(token)


def clear_pending_confirmations() -> None:
    """Clear all pending confirmations."""
    _pending_confirmations.clear()


def is_dangerous_tool(tool_name: str) -> bool:
    """Check if a tool requires confirmation.

    Args:
        tool_name: Name of the tool to check.

    Returns:
        True if the tool is considered dangerous and requires confirmation.
    """
    return tool_name in ["ui_close_window", "ui_terminate_process"]


def _cleanup_expired_tokens() -> None:
    """Remove expired tokens from registry (TTL-based cleanup)."""
    current_time = time.time()
    expired_tokens = [
        token for token, (_, timestamp) in _control_registry.items()
        if current_time - timestamp > _registry_ttl
    ]
    for token in expired_tokens:
        del _control_registry[token]


def _cleanup_lru() -> None:
    """Remove oldest entry if registry exceeds max size (LRU eviction)."""
    if len(_control_registry) >= _registry_max_size:
        oldest_token = min(
            _control_registry.keys(),
            key=lambda t: _control_registry[t][1]
        )
        del _control_registry[oldest_token]


def register_control(control: auto.Control) -> str:
    """Register a control and return a unique token.

    Args:
        control: The Control object to register.

    Returns:
        A unique token string (8 chars) that can be used to retrieve the control.
    """
    token = str(uuid.uuid4())[:8]
    _cleanup_expired_tokens()
    _cleanup_lru()
    _control_registry[token] = (control, time.time())
    return token


def get_control_by_token(token: str) -> Optional[auto.Control]:
    """Retrieve a control by its token.

    Validates that the control still exists before returning.
    Removes invalid tokens from the registry.

    Args:
        token: Token generated by register_control().

    Returns:
        Control object if valid and still exists, None otherwise.
    """
    if token not in _control_registry:
        return None

    control, _ = _control_registry[token]

    # Verify control still exists
    try:
        if control.Exists(0, 0):
            # Update timestamp on access
            _control_registry[token] = (control, time.time())
            return control
    except Exception:
        pass

    # Control is no longer valid, remove it
    del _control_registry[token]
    return None


def control_to_info(control: auto.Control, token: Optional[str] = None) -> ControlInfo:
    """Convert a Control object to ControlInfo model.

    Args:
        control: The uiautomation Control object.
        token: Optional token (if already registered).

    Returns:
        ControlInfo with extracted properties.
    """
    try:
        rect = control.BoundingRectangle
        rect_dict = {
            "left": rect.left,
            "top": rect.top,
            "right": rect.right,
            "bottom": rect.bottom,
        } if rect else None
    except Exception:
        rect_dict = None

    # Generate token if not provided
    if not token:
        token = register_control(control)

    return ControlInfo(
        handle=control.NativeWindowHandle or 0,
        token=token,
        name=control.Name or "",
        class_name=control.ClassName or "",
        control_type=control.ControlTypeName or "",
        automation_id=control.AutomationId or "",
        process_id=control.ProcessId or 0,
        enabled=control.IsEnabled if control.IsEnabled is not None else True,
        visible=not control.IsOffscreen if control.IsOffscreen is not None else True,
        rect=rect_dict,
    )


def find_control(selector: ControlSelector) -> Optional[auto.Control]:
    """Find a control using selector parameters.

    Args:
        selector: ControlSelector with search criteria.

    Returns:
        Found Control object or None if not found.
    """
    # Build search parameters
    search_params: Dict[str, Any] = {}
    if selector.name:
        search_params["Name"] = selector.name
    if selector.name_contains:
        search_params["SubName"] = selector.name_contains
    if selector.name_regex:
        search_params["RegexName"] = selector.name_regex
    if selector.class_name:
        search_params["ClassName"] = selector.class_name
    if selector.automation_id:
        search_params["AutomationId"] = selector.automation_id
    if selector.control_type:
        # Fix: Convert control_type string to actual ControlType value
        try:
            control_type_obj = getattr(auto, selector.control_type, None)
            if control_type_obj is not None:
                search_params["ControlType"] = control_type_obj
        except (AttributeError, TypeError):
            logger.warning(f"Unknown control type: {selector.control_type}")
    if selector.depth != 0xFFFFFFFF:
        search_params["searchDepth"] = selector.depth
    if selector.index > 1:
        search_params["foundIndex"] = selector.index

    # Get parent or root
    if selector.parent_handle:
        parent = auto.ControlFromHandle(selector.parent_handle)
        if not parent:
            return None
        search_params["searchFromControl"] = parent
    else:
        search_params["searchFromControl"] = auto.GetRootControl()

    # Find using generic Control
    return auto.Control(**search_params)


def get_control_by_handle(handle: int) -> Optional[auto.Control]:
    """Get a control by its handle.

    Args:
        handle: NativeWindowHandle of the control.

    Returns:
        Control object or None if not found.
    """
    if not handle:
        return None
    try:
        return auto.ControlFromHandle(handle)
    except Exception:
        return None


def format_error(
    code: str,
    message: str,
    suggestions: Optional[List[str]] = None,
    context: Optional[Dict[str, Any]] = None
) -> Dict[str, Any]:
    """Format an error response.

    Args:
        code: Error code identifier.
        message: Human-readable error message.
        suggestions: List of suggestions to resolve the error.
        context: Additional context about the error.

    Returns:
        Formatted error dictionary.
    """
    return {
        "success": False,
        "error": {
            "code": code,
            "message": message,
            "suggestions": suggestions or [],
            "context": context or {},
        }
    }


def format_success(data: Any = None) -> Dict[str, Any]:
    """Format a success response.

    Args:
        data: Optional data to include in the response.

    Returns:
        Formatted success dictionary.
    """
    return {
        "success": True,
        "data": data,
    }
